# Dockerfile for building an AppImage using a contained Kubernetes job
#
# podman build -f Dockerfile.k8s -t psarm-k8s . 
# podman push localhost/psarm-k8s [REPO]/davidk/psarm-k8s:latest
# 

FROM docker.io/balenalib/raspberrypi5

ARG BRANCH=k8s_job

RUN apt-get update && apt-get install -y wget git jq curl python3-pip

WORKDIR /ps

COPY k8s-helper.sh .

ENTRYPOINT ["./k8s-helper.sh"]
