# This is a Kubernetes job that builds PrusaSlicer
#
# Requirements:
# * Kubernetes Cluster with ARM nodes, nodes should have at least >= 16Gb RAM.
# * Ability to request a persistent volume (through a PVC) for build storage.
#
# Lab setup:
# * 4x Turing Pi RK1 32GB - running K3S with storage provided by Longhorn (NVMe drives + SSD over SATA)
# * 1x Radxa Rock5B 32GB 
#
# Creating the namespace:
# $ kubectl create ns prusaslicer
#
# Launching the job:
# $ kubectl apply -f k8s-build-job.yml -n prusaslicer
#
# Getting job details:
# $ kubectl get job -n prusaslicer
#
# Getting the pods:
# $ kubectl get pods --selector=job-name=psbuild64 -n prusaslicer
# NAME            READY   STATUS    RESTARTS   AGE
# psbuild64-s652n   1/1     Running   0          129m
#
# Following the log (psbuild64 to follow the aarch64 build, etc):
# $ kubectl logs -f jobs/psbuild64 -n prusaslicer
#
# To extract the AppImages after the build is complete (use release.yml or its variation
# for publishing):
# $ kubectl exec psbuild64-s652n -n prusaslicer -- bash -c "cd /build/PrusaSlicer-ARM.AppImage/;tar -zcf - *.AppImage" | tar -zxvf - -C ./
#
# Jobs persist after completing, to remove it, and any resources created by this file:
# $ kubectl delete -f k8s-build-job.yml -n prusaslicer
#
## ------------------------------------------
#
# Customized Longhorn StorageClass for jobs (replicas for additional durability are usually not needed)
# Uncomment the block below to apply, or change to a different StorageClass
#
## $ kubectl get storageclass
#
#---
#kind: StorageClass
#apiVersion: storage.k8s.io/v1
#metadata:
#  name: longhorn-singlereplica
#provisioner: driver.longhorn.io
#allowVolumeExpansion: true
#reclaimPolicy: Delete
#volumeBindingMode: Immediate
#parameters:
#  numberOfReplicas: "1"
##-------------------------------------------
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psbuild64-longhorn-pvc
  namespace: prusaslicer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-singlereplica
  resources:
    requests:
      storage: 20Gi
---
# https://kubernetes.io/docs/concepts/workloads/controllers/job/
apiVersion: batch/v1
kind: Job
metadata:
  name: psbuild64
  namespace: prusaslicer
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: psbuild64
        image: dtcooper/raspberrypi-os:latest
        command: ["/bin/sh"]
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
        args: ["-c","
          apt-get update;
          apt-get install -y sudo wget git jq curl python3-pip libwebkit2gtk-4.1-0 libwebkit2gtk-4.1-dev texinfo automake libboost-nowide-dev;
          mkdir /ps;
          cd /ps;
          wget https://raw.githubusercontent.com/davidk/PrusaSlicer-ARM.AppImage/k8s_job_sharun/containers/k8s-helper.sh;
          chmod +x ./k8s-helper.sh;
          export LANG=C.UTF-8;
          ./k8s-helper.sh aarch64 k8s_job_sharun
        "]
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 4000m
            memory: 20Gi
        volumeMounts:
          - name: psbuild64-data
            mountPath: /build
      restartPolicy: Never
      volumes:
        - name: psbuild64-data
          persistentVolumeClaim:
            claimName: psbuild64-longhorn-pvc
---